# Generated by Django 4.2.2 on 2023-06-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nevrpApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=400, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.FloatField(max_length=40)),
                ('longitude', models.FloatField(max_length=40)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=86400)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('type', models.CharField(choices=[('gd1', 'GD1'), ('gd2', 'GD2'), ('gd3', 'GD3')], max_length=10)),
                ('slug', models.SlugField(max_length=400, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='capacity',
            field=models.FloatField(default=1.0, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=10, max_length=400, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_after_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_before_time',
            field=models.IntegerField(default=86400),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('standard', 'STANDARD'), ('rapid', 'RAPID')], default='standard', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='order_value',
            field=models.FloatField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_code', to='nevrpApp.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sender_code',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sender_code', to='nevrpApp.node'),
            preserve_default=False,
        ),
    ]
