# Generated by Django 4.2.2 on 2023-06-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nevrpApp', '0003_remove_order_id_alter_order_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('code', models.CharField(max_length=400, primary_key=True, serialize=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.CharField(choices=[('1', 'Rảnh'), ('0', 'Bận')], default='1', max_length=5)),
                ('average_fee_transport', models.FloatField(default=0.1, max_length=10)),
                ('average_gas_consume', models.FloatField(default=0.02, max_length=10)),
                ('average_velocity', models.FloatField(default=60, max_length=10)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gas_price', models.FloatField(default=23000, max_length=10)),
                ('height', models.FloatField(blank=True, max_length=10, null=True)),
                ('length', models.FloatField(blank=True, max_length=10, null=True)),
                ('max_capacity', models.FloatField(default=500, max_length=10)),
                ('max_load_weight', models.FloatField(blank=True, max_length=10, null=True)),
                ('max_velocity', models.FloatField(blank=True, max_length=10, null=True)),
                ('min_velocity', models.FloatField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('1', 'Xe vận tải'), ('2', 'Xe tải 3 chỗ'), ('3', 'Xe tải 4 chỗ'), ('4', 'Xe máy')], default='4', max_length=100)),
                ('width', models.FloatField(blank=True, max_length=10, null=True)),
                ('vehicle_cost', models.FloatField(blank=True, max_length=10, null=True)),
                ('slug', models.SlugField(max_length=400, null=True, unique=True)),
                ('current_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='nevrpApp.node')),
                ('manager_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='nevrpApp.node')),
            ],
        ),
    ]
