# Generated by Django 4.2.2 on 2023-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nevrpApp', '0004_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='slug',
        ),
        migrations.AddField(
            model_name='node',
            name='capacity',
            field=models.FloatField(default=1000, max_length=40),
        ),
        migrations.AddField(
            model_name='node',
            name='district_code',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='province_code',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
