# Generated by Django 4.2.2 on 2023-06-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nevrpApp', '0005_remove_node_slug_node_capacity_node_district_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.AddField(
            model_name='order',
            name='time_loading',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_service',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
