# Generated by Django 4.2.2 on 2023-06-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nevrpApp', '0006_remove_order_slug_order_time_loading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='slug',
        ),
    ]
